<?php
/**
 |--------------------------------------------------------------------------|
 |   https://github.com/Bigjoos/                                            |
 |--------------------------------------------------------------------------|
 |   Licence Info: WTFPL                                                    |
 |--------------------------------------------------------------------------|
 |   Copyright (C) 2010 U-232 V5                                            |
 |--------------------------------------------------------------------------|
 |   A bittorrent tracker source based on TBDev.net/tbsource/bytemonsoon.   |
 |--------------------------------------------------------------------------|
 |   Project Leaders: Mindless, Autotron, whocares, Swizzles.               |
 |--------------------------------------------------------------------------|
  _   _   _   _   _     _   _   _   _   _   _     _   _   _   _
 / \ / \ / \ / \ / \   / \ / \ / \ / \ / \ / \   / \ / \ / \ / \
( U | - | 2 | 3 | 2 )-( S | o | u | r | c | e )-( C | o | d | e )
 \_/ \_/ \_/ \_/ \_/   \_/ \_/ \_/ \_/ \_/ \_/   \_/ \_/ \_/ \_/
 */
$lang = array(
    'block_settings' => "Paramètres des Blocs",
	'block_block' => "Bloc",
	'block_updated' => "Les paramètres des blocs ont été mis à jour!",
	'block_global' => "Paramètres généraux des blocs",
	'block_index' => "Paramètres d'affichage de l'index",
	'block_iealert' => "Activer l'alerte IE?",
	'block_iealert_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer l'alerte utilisateur IE.",
	'block_news' => "Activer les Nouvelles?",
	'block_news_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le Bloc des Nouvelles.",
	'block_shout' => "Activer la Shoutbox?",
	'block_shout_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer la Shoutbox.",
	'block_staff_shout' => "Activer la Shoutbox staff?",
	'block_staff_shout_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer la Shoutbox staff.",
	'block_active_user' => "Activer les Membres actifs?",
	'block_active_user_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Membres actifs.",
	'block_active_user24' => "Activer les Membres actifs des dernières 24 heures?",
	'block_active_user24_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Membres actifs des dernières 24 heures.",
	'block_active_irc' => "Activer les Membres actifs sur IRC?",
	'block_active_irc_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Membres actifs sur IRC.",
	'block_birthday' => "Activer les Anniversaires des membres?",
	'block_birthday_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Anniversaires des membres.",
	'block_stats' => "Activer les Stats du site?",
	'block_stats_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Stats du site.",
	'block_disclaimer' => "Activer les Mentions légales?",
	'block_disclaimer_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Mentions légales.",
	'block_latest_users' => "Activer les Derniers membres?",
	'block_latest_users_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Derniers membres?.",
	'block_forum_post' => "Activer les Derniers sujets du forum?",
	'block_forum_post_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Derniers sujets du forum.",
	'block_torrents' => "Activer les Derniers torrents?",
	'block_torrents_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Derniers torrents.",
	'block_torrents_scroll' => "Activer le Défilement des derniers torrents?",
	'block_torrents_scroll_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le défilement des derniers torrents.",
	'block_announcement' => "Activer les Annonces?",
	'block_announcement_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Annonces.",
	'block_donation' => "Activer la Progression des Dons?",
	'block_donation_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Progression des Dons.",
	'block_advertise' => "Activer la Publicité?",
	'block_advertise_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Publicité.",
	'block_radio' => "Activer la Radio?",
	'block_radio_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Radio.",
	'block_torrent_freak' => "Activer les News sur la sphère Torrent?",
	'block_torrent_freak_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc News sur la sphère BitTorrent.",
	'block_xmas' => "Activer le cadeau de Noël?",
	'block_xmas_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Cadeau de Noël.",
	'block_poll' => "Activer les Sondages?",
	'block_poll_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Sondages.",
	'block_movie' => "Activer le Film de la semaine?",
	'block_reqnoff' => "bloc setting à venir",
	///Stdhead Display Settings///
	'block_movie_set' => "Définir cette option sur \"Oui\" si vous souhaitez activer le bloc Film de la semaine.",
	'block_stdhead_settings' => "Paramètres d'affichage d'en-tête (Header)",
	'block_freelech' => "Freeleech?",
	'block_freelech_set' => "Activer l'alerte 'Freeleech' sur l'en-tête",
	'block_demotion' => "Rétrogradation?",
	'block_demotion_set' => "Activer l'alerte de rétrogradation",
	'block_message' => "Alerte messages?",
	'block_message_set' => "Activer l'alerte de messages",
	'block_staff_warnings' => "Avertissement de message staff?",
	'block_staff_warnings_set' => "Affiche un avertissement s'il y a un nouveau message pour le staff",
	'block_staff_reports' => "Alerte Staff?",
	'block_staff_reports_set' => "Activer les rapports d'alerte sur l'en-tête",
	'block_upload_alert' => "Alerte uploader?",
	'block_upload_alert_set' => "Activer les alertes uploader sur l'en-tête",
	'block_happyhour' => "Happyhour?",
	'block_happyhour_set' => "Activer les alertes Happyhour sur l'en-tête",
	'block_crazyhour' => "CrazyHour?",
	'block_crazyhour_set' => "Activer les alertes Crazyhour sur l'en-tête",
	'block_bug' => "Alerte d'incident?",
	'block_bug_set' => "Activer les alertes d'incident sur l'en-tête",
	'block_karma_contributions' => "Status du Karma?",
	'block_karma_contributions_set' => "Activer les alertes de contribution au Karma sur l'en-tête",
	'block_staff_tools' => "Bloc setting à venir",
	///Userdetails Display Settings////
	'block_userdetails' => "Paramètre d'affichage des détails de compte",
	'block_login_link' => "Lien d'identification rapide?",
	'block_login_link_set' => "Activer le lien d'identification rapide",
	'block_flush' => "Nettoyer les torrents?",
	'block_flush_set' => "Activer le nettoyage des torrents",
	'block_joined' => "Date d'inscription?",
	'block_joined_set' => "Activer la date d'inscription",
	'block_user_online_time' => "Durée de connection?",
	'block_user_online_time_set' => "Activer la durée de connection du membre",
	'block_browser_os' => "Détection du navigateur et de l'OS ?",
	'block_browser_os_set' => "Activer la détection du navigateur et de l'OS",
	'block_reputation' => "Réputation?",
	'block_reputation_set' => "Activer la réputation",
	'block_userhits' => "Top 50 utilisateur?",
	'block_userhits_set' => "Activer le top 50 utilisateur",
	'block_birthday_userdetails' => "Anniversaire?",
	'block_birthday_userdetails_set' => "Activer l'affichage de l'anniversaire",
	'block_contact' => "Informations de contact?",
	'block_contact_set' => "Activer les informations de contact",
	'block_iphistory' => "Historique des IPs?",
	'block_iphistory_set' => "Activer l'historique des IPs",
	'block_traffic' => "Traffic?",
	'block_traffic_set' => "Activer le traffic d'upload et de téléchargement",
	'block_shareratio' => "Ratio de partage?",
	'block_shareratio_set' => "Activer le ratio de partage",
	'block_seedtime' => "Ratio du temps de seed?",
	'block_seedtime_set' => "Activer le ratio du temps de seed",
	'block_seedbonus' => "Seedbonus?",
	'block_seedbonus_set' => "Activer le seedbonus",
	'block_ircstats' => "Stats IRC?",
	'block_ircstats_set' => "Activer les stats IRC",
	'block_conn_port' => "Connectivité et port?",
	'block_conn_port_set' => "Activer la connectivité et port",
	'block_avatar' => "Avatar?",
	'block_avatar_set' => "Activer l'avatar",
	'block_userclass' => "Classe du membre?",
	'block_userclass_set' => "Activer la classe du membre",
	'block_gender' => "Genre?",
	'block_gender_set' => "Activer le genre",
	'block_freeslot_freelech' => "Freeslots et Freeleech?",
	'block_freeslot_freelech_set' => "Activer les freeslots et freeleech",
	'block_torrent_comment' => "Commentaires de torrents?",
	'block_torrent_comment_set' => "Activer l'historique des commentaires de torrents",
	'block_forum_user_post' => "Sujets sur le forum?",
	'block_forum_user_post_set' => "Activer l'historique des sujets sur le forum",
	'block_invitedby' => "Invité par?",
	'block_invitedby_set' => "Activer 'Invité par'",
	'block_torrent_info' => "Information torrent?",
	'block_torrent_info_set' => "Activer les infos de seed, leech, snatched, upload des torrents",
	'block_completed' => "Complétés?",
	'block_completed_set' => "Activer les torrents complétés",
	'block_staff_snatched' => "Torrents téléchargés par le staff?",
	'block_staff_snatched_set' => "Activer les torrents téléchargés par le staff",
	'block_user_info' => "Information membre?",
	'block_user_info_set' => "Activer l'information membre",
	'block_show_pm' => "Montrer les PMs?",
	'block_show_pm_set' => "Activer le bouton d'envoi de messages privés",
	'block_report' => "Signalement?",
	'block_report_set' => "Activer l'option de signalement de membre",
	'block_user_status' => "Status du membre?",
	'block_user_status_set' => "Activer le status du membre",
	'block_user_comments' => "Commentaires du membre?",
	'block_user_comments_set' => "Activer les commentaires du membre",
	'block_showfriends' => "Afficher les amis?",
	'block_showfriends_set' => "Activer le bouton d'affichage des amis",
	'block_submit' => "Soumettre",
	'block_stdhead' => "Paramètres des blocs",
	'block_yes' => "Oui &nbsp;",
	'block_no' => "&nbsp; Non",
	'block_page_title' => "Redirection des blocs administrateur",
	'block_redir' => "Redirection...",
	'block_redir1' => "Redirection",
	'block_click_redir' => "Cliquez ici si vous n'êtes pas redirigé...",
);
?>
